Repository ak2j38/airbnb, pull requests merged in 2022-05, with the labels that each got.

#11 [#7] Feature search container
  iOS/.DS_Store
  iOS/Airbnb/.DS_Store
  iOS/Airbnb/Airbnb.xcodeproj/project.pbxproj
  iOS/Airbnb/Airbnb.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/Airbnb/Airbnb/Search/Model/SearchFavoriteLocationModel.swift
  iOS/Airbnb/Airbnb/Search/Model/SearchMainModel.swift
  iOS/Airbnb/Airbnb/Search/View/MyInfoCollectionViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SearchViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/SearchCellCommonType.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/SearchOneInARowCollectionViewCell.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/SearchTitleCollectionViewCell.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/SearchTwoInARowCollectionViewCell.swift
Labels: 📱iOS

#14 [#6] feat: Search bar 와 Search Controller 의 깊은 이해를 수반한 작업
  iOS/Airbnb/Airbnb.xcodeproj/project.pbxproj
  iOS/Airbnb/Airbnb.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/Airbnb/Airbnb/MyInfo/TabBar/TabBarViewController.swift
  iOS/Airbnb/Airbnb/Search/View/LocationViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SearchViewController.swift
Labels: enhancement, 📱iOS

#23 [#16] refactor: 숙소 찾기 화면에서 사용하지 않는 메서드 제거 및 주석 제거
  iOS/Airbnb/Airbnb/Search/View/LocationViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SearchViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/MultipleRowsCollectionViewController.swift
Labels: bug, 📱iOS

#33 Hotfix 20220525
  iOS/Airbnb/Airbnb/Search/View/MyInfoCollectionViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SearchViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/MultipleRowsCollectionViewContainerCell.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/MultipleRowsCollectionViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/SearchCellCommonType.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/SearchOneInARowCollectionViewCell.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/SearchTitleCollectionViewCell.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/SearchTwoInARowCollectionViewCell.swift
Labels: 📱iOS

#34 [#16] hotfix: 1주차 수요일 코드리뷰 반영(구찌)
  iOS/Airbnb/.DS_Store
  iOS/Airbnb/Airbnb.xcodeproj/project.pbxproj
  iOS/Airbnb/Airbnb/Search/.DS_Store
  iOS/Airbnb/Airbnb/Search/BackgroundViewController.swift
  iOS/Airbnb/Airbnb/Search/View/.DS_Store
  iOS/Airbnb/Airbnb/Search/View/LocationViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SearchViewController.swift
Labels: 📱iOS, hotfix

#36 [Feat] 예약 도메인 MockAPI 구현
  BE/src/main/java/com/ahoo/airbnb/reservation/Charge.java
  BE/src/main/java/com/ahoo/airbnb/reservation/Charges.java
  BE/src/main/java/com/ahoo/airbnb/reservation/MockReservationService.java
  BE/src/main/java/com/ahoo/airbnb/reservation/ReservationController.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/ReservationRequest.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/ReservationResponse.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/ReservationsResponse.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/RoomChargeRequest.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/RoomChargeResponse.java
Labels: ⚙️BE

#38 [Feat] 위시 도메인 MockAPI 구현
  BE/src/main/java/com/ahoo/airbnb/wish/MockWishService.java
  BE/src/main/java/com/ahoo/airbnb/wish/WishController.java
Labels: ⚙️BE

#39 [Feat] calendar modeling
  iOS/Airbnb/Airbnb.xcodeproj/project.pbxproj
  iOS/Airbnb/Airbnb/Search/DTO/SearchDayDTO.swift
  iOS/Airbnb/Airbnb/Search/Model/SearchCalendarModel.swift
  iOS/Airbnb/AirbnbTests/AirbnbCalendarModelTests.swift
Labels: 📱iOS

#41 [#6] feat: 숙소 찾기 VC 에 CollectionView, HeaderView, Cell 요소 작업
  iOS/Airbnb/Airbnb.xcodeproj/project.pbxproj
  iOS/Airbnb/Airbnb/Search/BackgroundViewController.swift
  iOS/Airbnb/Airbnb/Search/View/LocationViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SearchViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/HeaderReusableView.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/LocationCollectionViewCell.swift
  iOS/Airbnb/Airbnb/Source/Assets.xcassets/mockImage.imageset/Contents.json
  iOS/Airbnb/Airbnb/Source/Assets.xcassets/mockImage.imageset/mockImage.png
Labels: enhancement

#42 [Feat] Swagger 적용
  BE/build.gradle
  BE/src/main/java/com/ahoo/airbnb/HelloController.java
  BE/src/main/java/com/ahoo/airbnb/config/SwaggerConfig.java
  BE/src/main/java/com/ahoo/airbnb/reservation/ReservationController.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomController.java
  BE/src/main/java/com/ahoo/airbnb/wish/WishController.java
Labels: ⚙️BE

#47 [Feat] DB 설정 추가
  BE/build.gradle
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
Labels: ⚙️BE

#48 [Feat] 더미 데이터 생성
  BE/src/main/resources/sql/data.sql
  BE/src/main/resources/sql/schema.sql
Labels: ⚙️BE

#60 [deploy] 대망의 첫 번째 배포
  BE/build.gradle
  BE/src/main/java/com/ahoo/airbnb/HelloController.java
  BE/src/main/java/com/ahoo/airbnb/config/SwaggerConfig.java
  BE/src/main/java/com/ahoo/airbnb/member/MemberResponse.java
  BE/src/main/java/com/ahoo/airbnb/reservation/MockReservationService.java
  BE/src/main/java/com/ahoo/airbnb/reservation/ReservationController.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/ChargesResponse.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/ReservationRequest.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/ReservationResponse.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/ReservationsResponse.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/RoomChargeRequest.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/RoomChargeResponse.java
  BE/src/main/java/com/ahoo/airbnb/room/Address.java
  BE/src/main/java/com/ahoo/airbnb/room/Image.java
  BE/src/main/java/com/ahoo/airbnb/room/Images.java
  BE/src/main/java/com/ahoo/airbnb/room/MockRoomService.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomCondition.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomController.java
  BE/src/main/java/com/ahoo/airbnb/room/dtos/RoomDetailResponse.java
  BE/src/main/java/com/ahoo/airbnb/room/dtos/RoomRequest.java
  BE/src/main/java/com/ahoo/airbnb/room/dtos/RoomResponse.java
  BE/src/main/java/com/ahoo/airbnb/wish/MockWishService.java
  BE/src/main/java/com/ahoo/airbnb/wish/WishController.java
Labels: ⚙️BE

#65 [feat] 캘린더에서 툴바 활성화
  iOS/Airbnb/Airbnb.xcodeproj/project.pbxproj
  iOS/Airbnb/Airbnb/Info.plist
  iOS/Airbnb/Airbnb/Network/NetworkCommonComponents.swift
  iOS/Airbnb/Airbnb/Network/NetworkServices.swift
  iOS/Airbnb/Airbnb/Network/SearchUseCase.swift
  iOS/Airbnb/Airbnb/Search/Calendar/View/CalendarViewController.swift
  iOS/Airbnb/Airbnb/Search/DTO/Reservations.swift
  iOS/Airbnb/Airbnb/Search/DTO/SearchDayDTO.swift
  iOS/Airbnb/Airbnb/Search/Model/LocationModel.swift
  iOS/Airbnb/Airbnb/Search/Model/ReservationModel.swift
  iOS/Airbnb/Airbnb/Search/Model/SearchModel.swift
  iOS/Airbnb/Airbnb/Search/View/LocationViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SearchViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/HeaderReusableView.swift
  iOS/Airbnb/Airbnb/Search/View/SubView/LocationCollectionViewCell.swift
  iOS/Airbnb/AirbnbTests/AirbnbSearchUseCaseResponseTests.swift
Labels: enhancement

#68 [Feat] 그래프 그리고 슬라이더와 연동
  iOS/Airbnb/Airbnb.xcodeproj/project.pbxproj
  iOS/Airbnb/Airbnb/Search/Calendar/View/CalendarViewController.swift
  iOS/Airbnb/Airbnb/Search/Graph/View/ColumnGraphView.swift
  iOS/Airbnb/Airbnb/Search/Graph/View/PriceGraphViewController.swift
  iOS/Airbnb/Airbnb/Source/CommonColors.swift
Labels: 📱iOS

#69 feat: Calendar VC 초기작업
  iOS/Airbnb/Airbnb.xcodeproj/project.pbxproj
  iOS/Airbnb/Airbnb/Search/BackgroundViewController.swift
  iOS/Airbnb/Airbnb/Search/Calendar/View/CalendarViewCell.swift
  iOS/Airbnb/Airbnb/Search/Calendar/View/CalendarViewController.swift
  iOS/Airbnb/Airbnb/Search/View/LocationViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SearchViewController.swift
Labels: enhancement
