Repository ak2j38/airbnb, pull requests merged in 2022-06, with the labels that each got.

#71 [Feat] 숙소 요금 계산 API 구현 완료
  BE/src/main/java/com/ahoo/airbnb/entity/Address.java
  BE/src/main/java/com/ahoo/airbnb/entity/ChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/entity/Coordinate.java
  BE/src/main/java/com/ahoo/airbnb/entity/Member.java
  BE/src/main/java/com/ahoo/airbnb/entity/Reservation.java
  BE/src/main/java/com/ahoo/airbnb/entity/Room.java
  BE/src/main/java/com/ahoo/airbnb/entity/RoomChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/entity/RoomImage.java
  BE/src/main/java/com/ahoo/airbnb/entity/Wish.java
  BE/src/main/java/com/ahoo/airbnb/exception/ErrorResponse.java
  BE/src/main/java/com/ahoo/airbnb/exception/ExceptionMessage.java
  BE/src/main/java/com/ahoo/airbnb/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/ahoo/airbnb/reservation/ChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/ChargePolicyType.java
  BE/src/main/java/com/ahoo/airbnb/reservation/MockReservationService.java
  BE/src/main/java/com/ahoo/airbnb/reservation/ReservationController.java
  BE/src/main/java/com/ahoo/airbnb/reservation/ReservationService.java
  BE/src/main/java/com/ahoo/airbnb/reservation/WeekdayPolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/WeekendPolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/AccommodationChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/AccommodationTaxChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/ChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/ChargePolicyType.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/CleaningChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/ServiceChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/chargepolicy/WeeklyDiscountChargePolicy.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/ChargesResponse.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/RoomChargeRequest.java
  BE/src/main/java/com/ahoo/airbnb/reservation/dtos/RoomChargeResponse.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomRepository.java
  BE/src/main/java/com/ahoo/airbnb/utils/DateUtils.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/sql/data.sql
  BE/src/main/resources/sql/schema.sql
  BE/src/test/java/com/ahoo/airbnb/data/TestData.java
  BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
Labels: ⚙️BE

#72 [Feat] Rage Slider 작업 진행
  iOS/.gitignore
  iOS/Airbnb/Airbnb.xcodeproj/project.pbxproj
  iOS/Airbnb/Airbnb/Search/CommonTableViewController.swift
  iOS/Airbnb/Airbnb/Search/Graph/View/ColumnGraphView.swift
  iOS/Airbnb/Airbnb/Search/Graph/View/CustomRangeSlider.swift
  iOS/Airbnb/Airbnb/Search/Graph/View/CustomRangeSliderThumbLayer.swift
  iOS/Airbnb/Airbnb/Search/Graph/View/CustomRangeSliderTrackLayer.swift
  iOS/Airbnb/Airbnb/Search/Graph/View/PriceGraphViewController.swift
  iOS/Airbnb/Airbnb/Search/View/SearchHeadCountViewController.swift
  iOS/Airbnb/Airbnb/Source/CommonColors.swift
Labels: 📱iOS

#77 [Feat] DB 운영환경 구축
  BE/src/main/resources/application-dev.yml
  BE/src/main/resources/application-prod.yml
Labels: ⚙️BE

#78 [Feat] 위시 API 구현
  BE/src/main/java/com/ahoo/airbnb/entity/Coordinate.java
  BE/src/main/java/com/ahoo/airbnb/entity/Room.java
  BE/src/main/java/com/ahoo/airbnb/entity/Wish.java
  BE/src/main/java/com/ahoo/airbnb/exception/ExceptionMessage.java
  BE/src/main/java/com/ahoo/airbnb/member/MemberRepository.java
  BE/src/main/java/com/ahoo/airbnb/room/dtos/RoomResponse.java
  BE/src/main/java/com/ahoo/airbnb/wish/MockWishService.java
  BE/src/main/java/com/ahoo/airbnb/wish/WishController.java
  BE/src/main/java/com/ahoo/airbnb/wish/WishRepository.java
  BE/src/main/java/com/ahoo/airbnb/wish/WishService.java
Labels: ⚙️BE

#79 [Feat] 숙소 검색 API 구현
  BE/build.gradle
  BE/src/main/java/com/ahoo/airbnb/config/QuerydslConfig.java
  BE/src/main/java/com/ahoo/airbnb/entity/Room.java
  BE/src/main/java/com/ahoo/airbnb/reservation/ReservationController.java
  BE/src/main/java/com/ahoo/airbnb/reservation/ReservationService.java
  BE/src/main/java/com/ahoo/airbnb/room/MockRoomService.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomController.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomCustomRepository.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomRepository.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomRepositoryImpl.java
  BE/src/main/java/com/ahoo/airbnb/room/RoomService.java
  BE/src/main/java/com/ahoo/airbnb/room/dtos/RoomResponse.java
  BE/src/test/java/com/ahoo/airbnb/reservation/ReservationServiceTest.java
Labels: ⚙️BE

#80 [Refactor, Feature] 숙소 검색 공통 테이블 뷰 작업
  iOS/Airbnb/Airbnb.xcodeproj/project.pbxproj
  iOS/Airbnb/Airbnb/Search/Calendar/View/CalendarViewController.swift
  iOS/Airbnb/Airbnb/Search/CommonTableViewController.swift
  iOS/Airbnb/Airbnb/Search/DTO/SearchInfo.swift
  iOS/Airbnb/Airbnb/Search/Graph/View/PriceGraphViewController.swift
  iOS/Airbnb/Airbnb/Search/SearchIfnoTracking/SearchInfoTrackingModel.swift
  iOS/Airbnb/Airbnb/Search/SearchIfnoTracking/SearchInfoTrackingTableViewCell.swift
  iOS/Airbnb/Airbnb/Search/SearchIfnoTracking/SearchInfoTrackingTableViewDataSource.swift
  iOS/Airbnb/Airbnb/Search/SearchIfnoTracking/SearchInfoTrackingTableViewDelegate.swift
  iOS/Airbnb/Airbnb/Search/SearchIfnoTracking/SearchInfoTrackingViewController.swift
  iOS/Airbnb/Airbnb/Search/View/LocationViewController.swift
Labels: 📱iOS

#82 [feat, chore] 캘린더 작업 및 백 브랜치와 병합
  iOS/.DS_Store
  iOS/Airbnb/.DS_Store
  iOS/Airbnb/Airbnb.xcodeproj/project.pbxproj
  iOS/Airbnb/Airbnb.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/Airbnb/Airbnb/.DS_Store
  iOS/Airbnb/Airbnb/Search/.DS_Store
  iOS/Airbnb/Airbnb/Search/Calendar/View/CalendarHearderView.swift
  iOS/Airbnb/Airbnb/Search/Calendar/View/CalendarViewCell.swift
  iOS/Airbnb/Airbnb/Search/Calendar/View/CalendarViewController.swift
  iOS/Airbnb/Airbnb/Search/Calendar/View/WeekdayView.swift
  iOS/Airbnb/Airbnb/Search/DTO/Day.swift
  iOS/Airbnb/Airbnb/Search/DTO/SearchDayDTO.swift
  iOS/Airbnb/Airbnb/Search/Model/CalendarModel.swift
  iOS/Airbnb/Airbnb/Search/Model/SearchCalendarModel.swift
  iOS/Airbnb/Airbnb/Search/View/LocationViewController.swift
  iOS/Airbnb/AirbnbTests/AirbnbCalendarModelTests.swift
Labels: enhancement

#88 [fix] Calendar 에서 Cell 관리
  iOS/.DS_Store
  iOS/Airbnb/Airbnb/Search/Calendar/View/CalendarViewCell.swift
  iOS/Airbnb/Airbnb/Search/Calendar/View/CalendarViewController.swift
  iOS/Airbnb/Airbnb/Search/Calendar/View/WeekdayView.swift
  iOS/Airbnb/Airbnb/Search/Model/CalendarModel.swift
  iOS/Airbnb/Airbnb/Search/Model/LocationModel.swift
  iOS/Airbnb/Airbnb/Search/SearchIfnoTracking/SearchInfoTrackingModel.swift
  iOS/Airbnb/Airbnb/Search/View/LocationViewController.swift
  iOS/Airbnb/Airbnb/Source/AppDelegate.swift
Labels: bug, enhancement
